services:
  wms_db:
    container_name: wms_db
    image: postgres:17
    ports:
      - 8000:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=wms_db
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: putra4648/backend
    depends_on:
      wms_db:
        condition: service_healthy
      # keycloak:
      #   condition: service_healthy
    build:
      context: .
    container_name: backend
    ports:
      - 7000:7000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wms_db:5432/wms_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
    networks:
      - wms-network

  frontend:
    image: putra4648/frontend
    build:
      context: ./web
    container_name: wms-web
    ports:
      - 3001:3000
    networks:
      - wms-network
    depends_on:
      - backend

networks:
  wms-network:
    driver: bridge
