name: Docker Compose Action

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-run:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Docker compose run DB
      #   run: docker compose up -d wms_db

      # - name: Docker compose run Keycloak
      #   run: docker compose up -d keycloak

      - name: Docker compose run
        run: docker compose up -d
