name: Docker Compose Action

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker compose run DB
        run: docker compose up -d wms_db

      - name: Docker compose run Keycloak
        run: docker compose up -d keycloak

      - name: Docker compose run App
        run: docker compose up -d app
