name: Docker Compose Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Run docker compose
        run: docker compose up -d
      - name: Build app
        run: mvn clean package
      - name: Run App
        run: mvn spring-boot:run
