name: Spring Boot Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run tests with Maven
      run: ./mvnw clean test --batch-mode --update-snapshots

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Test Results
        path: target/surefire-reports/TEST-*.xml
        reporter: java-junit
        fail-on-error: true
